version: 2.1
jobs:

  # Download the release artefacts
  dl_release:
    docker:
      - image: rdclda/ci-export-release
    working_directory: ~/release
    steps:
      # Checkout the repository
      - checkout

      # Create workspace output folder
      - run:
          name: Create workspace directory
          command: mkdir -p ./artefacts
      
      # Retrieve the artefacts
      - run:
          name: Export artefacts to its defined destination
          command: |
            download-release \
              --source=release-source.json \
              --manifest=release-manifest.json \
              --destination=./artefacts

      # Copy the release manifest into the workspace
      - run:
          name: Copy release manifest
          command: cp ./release-manifest.json artefacts/

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/release
          # Must be relative path from root
          paths:
             - artefacts/

  # Validate the downloaded release
  val_release:
    docker:
      - image: rdclda/ci-export-release
    working_directory: ~/release
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/release

      # Retrieve the artefacts
      - run:
          name: Validate the artefacts
          command: |
            validate-release \
              --source=./artefacts \
              --manifest=./artefacts/release-manifest.json
       
  # # Publish the generated HTML to the RDC Website to PCF
  # publish_pcf:
  #   docker:
  #     - image: rdclda/ci-cloudfoundry:latest
  #   working_directory: ~/rdc-blogs
  #   steps:
  #     - attach_workspace:
  #         # Must be absolute path or relative path from working_directory
  #         at: ~/rdc-blogs

  #     # Publish into separate folder
  #     - deploy:
  #         name: Upload content to Pivotal CloudFoundry
  #         command: |
  #           cf login -a $CF_API_ENDPOINT -o $CF_ORG -u $CF_USER -p $CF_PASS -s $CF_SPACE && \
  #           cf push rdc-blogs -b staticfile_buildpack -n rdc-blogs -s cflinuxfs3 -p ./dist

# Glue the jobs together
workflows:
  version: 2
  deploy:
    jobs:
      - dl_release
      - val_release:
          requires:
            - dl_release
      # - publish_pcf:
      #     requires:
      #       - validate
      #     filters:
      #       branches:
      #         only: master%