version: 2.1
jobs:
  # Export the release
  download_release:
    docker:
      - image: rdclda/ci-export-release
    working_directory: ~/ci-workspace
    steps:
      # Checkout the repository
      - checkout

      # Download the release
      - run:
          name: Download the release to its defined destination
          command: |
            download-release \
              --source=release-source.json \
              --manifest=release-manifest.json \
              --destination=./release

      # Copy the release manifest into the workspace
      - run:
          name: Bundle release manifest 
          command: cp ./release-manifest.json release/

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/ci-workspace
          # Must be relative path from root
          paths:
             - release/

  # Validate the downloaded release
  validate_release:
    docker:
      - image: rdclda/ci-export-release
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      # Retrieve the release
      - run:
          name: Validate the release
          command: |
            validate-release \
              --source=./release \
              --manifest=./release/release-manifest.json
 
  # Provision infrastructure
  provision_infra:
    docker:
      - image: rdclda/ci-openshift-infra
    working_directory: ~/ci-workspace
    steps:
      # Checkout the repository for the infra manifest
      - checkout

      # Retrieve the release
      - run:
          name: Create AWS OpenShift infrastructure
          command: |
            init-infra \
              --manifest=./infra-manifest.json

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/ci-workspace
          # Must be relative path from root
          paths:
             - infra/

  # publish_pcf:
  #   docker:
  #     - image: rdclda/ci-cloudfoundry:latest
  #   working_directory: ~/rdc-blogs
  #   steps:
  #     - attach_workspace:
  #         # Must be absolute path or relative path from working_directory
  #         at: ~/rdc-blogs

  #     # Publish into separate folder
  #     - deploy:
  #         name: Upload content to Pivotal CloudFoundry
  #         command: |
  #           cf login -a $CF_API_ENDPOINT -o $CF_ORG -u $CF_USER -p $CF_PASS -s $CF_SPACE && \
  #           cf push rdc-blogs -b staticfile_buildpack -n rdc-blogs -s cflinuxfs3 -p ./dist

# Glue the jobs together
workflows:
  version: 2
  deploy_cbx:
    jobs:
      - download_release
      - validate_release:
          requires:
            - download_release
      - provision_infra:
          filters:
            branches:
              only: master%