version: 2.1

jobs:

  # Export the release
  download_release:
    docker:
      - image: rdclda/ci-export-release
    working_directory: ~/ci-workspace
    steps:
      # Checkout the repository
      - checkout

      # Create the release dir
      - run:
          name: Create release dir
          command: mkdir -p ./release

      # Download the release
      - run:
          name: Download the release to its defined release dir
          command: |
            download-release \
              --source=release-source.json \
              --manifest=release-manifest.json \
              --destination=./release

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/ci-workspace
          # Must be relative path from root
          paths:
             - release/

  # Validate the release
  validate_release:
    docker:
      - image: rdclda/ci-export-release
    working_directory: ~/ci-workspace
    steps:
      # Checkout the repository
      - checkout
      
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      # Retrieve the release
      - run:
          name: Validate the release
          command: |
            validate-release \
              --source=./release \
              --manifest=./release-manifest.json

  # Dockerize the release
  dockerize_release:
    docker:
      - image: rdclda/ci-docker-build
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace
      
      # Enable external Docker engine 
      - setup_remote_docker  
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      # Build the images(s)
      - run:
          name: Dockerize the release
          command: |
            dockerize-release \
              --source=./release \
              --manifest=./release/release-manifest.json
 
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

      # - deploy:
      #     name: Push application Docker image
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         login="$(aws ecr get-login)"
      #         ${login}
      #         docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #         docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #       fi

  # Init cloud infrastructure
  init_cloud_infra:
    docker:
      - image: rdclda/ci-cloud-infra
    working_directory: ~/ci-workspace
    steps:
      # Checkout the repository for the infra manifest
      - checkout

      # Create the config infra dir
      - run:
          name: Create config data dir
          command: mkdir -p ./infra

      # Setup VPCs, networks, DNS, etc...
      - run:
          name: Init cloud infrastructure
          command: |
            cloud-infra \
              --manifest=./infra-manifest.json \
              --config-data=./infra \
              --action=init

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/ci-workspace
          # Must be relative path from root
          paths:
             - infra/

  # Init Openshift infrastructure
  init_openshift_infra:
    docker:
      - image: rdclda/ci-cloud-infra
    working_directory: ~/ci-workspace
    steps:
      # Checkout the repository for the infra manifest
      - checkout

      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      # Setup VPCs, networks, DNS, etc...
      - run:
          name: Init OpenShift infrastructure
          command: |
            openshift-infra \
              --manifest=./infra-manifest.json \
              --config-data=./infra \
              --action=init

      # - persist_to_workspace:
      #     # Must be an absolute path, or relative path from working_directory
      #     root: ~/ci-workspace
      #     # Must be relative path from root
      #     paths:
      #        - infra/

  # Init channel middleware infrastructure
  init_channel_mw_infra:
    docker:
      - image: rdclda/ci-cloud-infra
    working_directory: ~/ci-workspace
    steps:
      # Checkout the repository for the infra manifest
      - checkout

      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace
      
          # Setup VPCs, networks, DNS, etc...
      - run:
          name: Init channel middleware infrastructure
          command: |
            channel-middleware-infra \
              --manifest=./infra-manifest.json \
              --config-data=./infra \
              --action=init

      # - persist_to_workspace:
      #     # Must be an absolute path, or relative path from working_directory
      #     root: ~/ci-workspace
      #     # Must be relative path from root
      #     paths:
      #        - infra/

  # Init backend middleware infrastructure
  init_backend_mw_infra:
    docker:
      - image: rdclda/ci-cloud-infra
    working_directory: ~/ci-workspace
    steps:
      # Checkout the repository for the infra manifest
      - checkout

      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      # Setup VPCs, networks, DNS, etc...
      - run:
          name: Init backend middleware infrastructure
          command: |
            backend-middleware-infra \
              --manifest=./infra-manifest.json \
              --config-data=./infra \
              --action=init

      # - persist_to_workspace:
      #     # Must be an absolute path, or relative path from working_directory
      #     root: ~/ci-workspace
      #     # Must be relative path from root
      #     paths:
      #        - infra/

  # Destroy infrastructure
  destroy_cloud_infra:
    parameters:
      openshift_hosts:
        type: boolean
        default: false
      channel_hosts:
        type: boolean
        default: false
      backend_hosts:
        type: boolean
        default: false

    docker:
      - image: rdclda/ci-cloud-infra
    working_directory: ~/ci-workspace
    steps:
      # Checkout the repository
      - checkout

      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      - when:
          condition: << parameters.openshift_hosts >>
          steps:
            # Destroy OpenShift infrastructure
            - run:
                name: Destroy OpenShift infrastructure
                command: |
                  openshift-infra \
                    --manifest=./infra-manifest.json \
                    --config-data=./infra \
                    --action=destroy

      - when:
          condition: << parameters.channel_hosts >>
          steps:
            # Destroy Channel middleware infrastructure
            - run:
                name: Destroy Channel middleware infrastructure
                command: |
                  channel-middleware-infra \
                    --manifest=./infra-manifest.json \
                    --config-data=./infra \
                    --action=destroy

      - when:
          condition: << parameters.backend_hosts >>
          steps:
            # Destroy Backend middleware infrastructure
            - run:
                name: Destroy Backend middleware infrastructure
                command: |
                  backend-middleware-infra \
                    --manifest=./infra-manifest.json \
                    --config-data=./infra \
                    --action=destroy

      # Destroy VPCs, networks, DNS, etc...
      - run:
          name: Destroy cloud infrastructure
          command: |
            cloud-infra \
              --manifest=./infra-manifest.json \
              --config-data=./infra \
              --action=destroy

  # Provision OpenShift
  provision_openshift_middleware:
    parameters:
      install:
        type: boolean
        default: true
    docker:
      - image: rdclda/ci-middleware-infra
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      - when:
          condition: << parameters.install >>
          steps:
            # Deploy the software
            - run:
                name: Deploy OpenShift
                command: |
                  deploy-openshift \
                    --manifest=./infra-manifest.json \
                    --config-data=./infra

  # Provision channel middleware
  provision_channel_middleware:
    parameters:
      install:
        type: boolean
        default: true
    docker:
      - image: rdclda/ci-middleware-infra
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      - when:
          condition: << parameters.install >>
          steps:
            # Deploy the software
            - run:
                name: Deploy Channel Middleware
                command: |
                  deploy-channel-middleware \
                    --manifest=./infra-manifest.json \
                    --config-data=./infra

  # Provision backend middleware
  provision_backend_middleware:
    parameters:
      install:
        type: boolean
        default: true
    docker:
      - image: rdclda/ci-middleware-infra
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      - when:
          condition: << parameters.install >>
          steps:
            # Deploy the software
            - run:
                name: Deploy backend Middleware
                command: |
                  deploy-backend-middleware \
                    --manifest=./infra-manifest.json \
                    --config-data=./infra

  # Provision Vault service
  provision_vault_service:
    parameters:
      install:
        type: boolean
        default: false
    docker:
      - image: rdclda/ci-vault-infra
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      - when:
          condition: << parameters.install >>
          steps:
            - run:
                name: Install and configure HashiCorp Vault infrastructure
                command: |
                  vault-install \
                    --manifest=./infra/infra-manifest.json \
                    --config-data=./infra

  # Provision LogDNA infrastructure
  provision_logdna_monitor:
    parameters:
      install:
        type: boolean
        default: false
    docker:
      - image: rdclda/ci-logdna-infra
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      - when:
          condition: << parameters.install >>
          steps:
            - run:
                name: Configure LogDNA infrastructure
                command: |
                  logdna-install \
                    --manifest=./infra/infra-manifest.json \
                    --config-data=./infra

  # Provision DataDog infrastructure
  provision_datadog_monitor:
    parameters:
      install:
        type: boolean
        default: false
    docker:
      - image: rdclda/ci-datadog-infra
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      - when:
          condition: << parameters.install >>
          steps:
            - run:
                name: Configure DataDog infrastructure
                command: |
                  datadog-install \
                    --manifest=./infra/infra-manifest.json \
                    --config-data=./infra

  # Provision SysDig infrastructure
  provision_sysdig_monitor:
    parameters:
      install:
        type: boolean
        default: false
    docker:
      - image: rdclda/ci-sysdig-infra
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      - when:
          condition: << parameters.install >>
          steps:
            - run:
                name: Configure SysDig infrastructure
                command: |
                  sysdig-install \
                    --manifest=./infra/infra-manifest.json \
                    --config-data=./infra

  # Deploy release
  deploy_release:
    docker:
      - image: rdclda/ci-deploy-release
    working_directory: ~/ci-workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ci-workspace

      # Retrieve the release
      - run:
          name: Deploy the release
          command: |
            deploy-release \
              --source=./release \
              --manifest=./release/release-manifest.json  

# Glue the jobs together
workflows:
  version: 2
  compose-provision-test-release:
    jobs:
      # 
      # Compose release
      - download_release
      - validate_release:
          requires:
            - download_release
      # 
      # Deploy Cloud infra      
      - init_cloud_infra:
          requires:
            - validate_release
      - init_openshift_infra:
          requires:
            - init_cloud_infra
      - init_channel_mw_infra:
          requires:
            - init_cloud_infra
      - init_backend_mw_infra:
          requires:
            - init_cloud_infra
      # 
      # Deploy middleware deployments
      # - provision_openshift_middleware:
      #     install: true
      #     requires: 
      #       - provision_cloud_infra
      # - provision_channel_middleware:
      #     install: true
      #     requires: 
      #       - provision_cloud_infra
      # - provision_backend_middleware:
      #     install: true
      #     requires: 
      #       - provision_cloud_infra
      # # 
      # # Deploy additional service components
      # - provision_vault_service:
      #     install: false
      #     requires:
      #       - provision_cloud_infra
      #       - provision_openshift_middleware
      # # 
      # # Deploy monitoring components
      # - provision_logdna_monitor:
      #     install: false
      #     requires:
      #       - provision_cloud_infra
      #       - provision_openshift_middleware
      # - provision_datadog_monitor:
      #     install: false
      #     requires:
      #       - provision_cloud_infra
      #       - provision_openshift_middleware
      #       - provision_channel_middleware
      #       - provision_backend_middleware
      # - provision_sysdig_monitor:
      #     install: false
      #     requires:
      #       - provision_cloud_infra
      #       - provision_openshift_middleware
      # # 
      # # Application deployments
      # - dockerize_release:
      #     requires:
      #       - provision_openshift_middleware
      # - deploy_release:
      #     requires:
      #       - dockerize_release
      #       - provision_vault_service
      - request_destroy:
          type: approval
          requires:
            - init_openshift_infra
            - init_channel_mw_infra
            - init_backend_mw_infra
      - destroy_cloud_infra:
          requires:
            - request_destroy